-- Action Matrix Schema v4 (PostgreSQL Compatible)
-- Migrated from Oracle v3

-- 1. Tracker table
-- Used to generate ACM IDs based on PO counts.
CREATE TABLE ACM_TRACKER (
    PO_CODE VARCHAR(5),   
    SL NUMERIC,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ACM_TRACKER_PK PRIMARY KEY (PO_CODE, SL)
);

-- 2. Master table
-- Main information about the action matrix.
CREATE TABLE ACM_MASTER (
    ACM_ID VARCHAR(60),
    PO_CODE VARCHAR(5) NOT NULL,
    VISITING_DATE DATE NOT NULL,
    
    OBSERVATION_DEPT VARCHAR(60) NOT NULL, -- OPERATION/AUDIT
    
    OBSERVATION_CATEGORY VARCHAR(500) NOT NULL, -- FINANCIAL/OPERATIONAL
    VISIT_TYPE VARCHAR(20) NOT NULL, -- ONSITE/OFFSITE
    VISIT_CATEGORY VARCHAR(60) NOT NULL, -- REGULAR VISIT/MANAGEMENT AUDIT
    
    LETTER_ISSUE_DATE DATE, 
    LETTER_RESPONSE_DATE DATE, -- TENTATIVE DATE TO GET RESPONSE FROM PO
    
    PKSF_OBSERVATION TEXT NOT NULL,
    DIRECTION_TO_PO TEXT NOT NULL,
    
    ACTION_MATRIX CHAR(1) CHECK (ACTION_MATRIX IN ('Y', 'N')), 
    
    PO_INBOX CHAR(1) CHECK (PO_INBOX IN ('Y', 'N')), 
    IS_EDITABLE_BY_PO CHAR(1) CHECK (IS_EDITABLE_BY_PO IN ('Y', 'N')), 
    PRIORITY VARCHAR(10), -- HIGH/MEDIUM/LOW
    
    CREATED_BY VARCHAR(20),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(20),
    UPDATED_AT TIMESTAMP,
    
    STATUS VARCHAR(60), -- FINAL STATUS. RUNNING/COMPLETED/CLOSED/DRAFT
    RESOLUTION_STATUS VARCHAR(60) -- RESOLVED/NOT_RESOLVED
    CONSTRAINT PK_ACM_MASTER PRIMARY KEY (ACM_ID)
);

-- 3. File attachment table for master
CREATE TABLE ACM_MASTER_FILE_ATTACHMENT (
    ACM_ID VARCHAR(60),
    SL NUMERIC,
    
    FILE_NAME VARCHAR(400),
    FILE_PATH VARCHAR(1000) NOT NULL,
    FILE_TYPE VARCHAR(20),
    FILE_SIZE NUMERIC, 
    
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ACM_MASTER_FILE_ATTACHMENT PRIMARY KEY (ACM_ID, SL),
    CONSTRAINT FK_ACM_MFA_MASTER FOREIGN KEY (ACM_ID) REFERENCES ACM_MASTER(ACM_ID)
);

-- 4. Movement table
-- Holds the movement information of acm master.
CREATE TABLE ACM_MOVEMENT (
    ACM_ID VARCHAR(60),
    SL NUMERIC,
    
    FROM_PARTY VARCHAR(20) NOT NULL, -- PKSF/PO
    ITEM_FROM VARCHAR(20),
    
    TO_PARTY VARCHAR(20) NOT NULL, -- PKSF/PO
    ITEM_TO VARCHAR(20),
    
    ACTION_TYPE VARCHAR(60), -- FORWARD/BACKWARD/APPROVED
    REMARKS TEXT,
    
    STATUS VARCHAR(50) DEFAULT 'RUNNING',
    
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(20),
    CONSTRAINT PK_ACM_MOVEMENT PRIMARY KEY (ACM_ID, SL),
    CONSTRAINT FK_ACM_MOV_MASTER FOREIGN KEY (ACM_ID) REFERENCES ACM_MASTER(ACM_ID)
);

-- 5. Comments table
CREATE TABLE ACM_COMMENTS (
    ACM_ID VARCHAR(60),
    SL NUMERIC,
    
    COMMENT_SOURCE VARCHAR(20) NOT NULL, -- PKSF/PO
    
    COMMENT_SHORT VARCHAR(20), -- EKMOT/DIMOT
    COMMENT_DETAIL TEXT NOT NULL, -- ACTUAL COMMENT
    
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_ACM_COMMENTS PRIMARY KEY (ACM_ID, SL),
    CONSTRAINT FK_ACM_COM_MASTER FOREIGN KEY (ACM_ID) REFERENCES ACM_MASTER(ACM_ID)
);

-- 6. File attachment table for comments
CREATE TABLE ACM_COMMENTS_FILE_ATTACHMENT (
    ACM_ID VARCHAR(60),
    SL NUMERIC,
    FILE_ID NUMERIC, -- 1 COMMENT CAN HAVE MULTIPLE FILES
    
    FILE_UPLOAD_BY VARCHAR(10), -- PO/PKSF
    
    FILE_NAME VARCHAR(400),
    FILE_PATH VARCHAR(1000) NOT NULL,
    FILE_TYPE VARCHAR(20),
    FILE_SIZE NUMERIC, 
    
    CREATED_BY VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_ACM_COMMENTS_FILE_ATTACHMENT PRIMARY KEY (ACM_ID, SL, FILE_ID),
    CONSTRAINT FK_ACM_CFA_COMMENTS FOREIGN KEY (ACM_ID, SL) REFERENCES ACM_COMMENTS(ACM_ID, SL)
);
