-- Action Matrix Schema v3
-- Includes fixed syntax and integrated Foreign Key constraints

-- This is the tracker table that holds the count of acm id for each po. 
-- This is needed to generate the acm id in the acm master table.
CREATE TABLE ACM_TRACKER (
    PO_CODE VARCHAR2(5),   
    SL INTEGER,
    CREATED_AT DATE,
    CONSTRAINT ACM_TRACKER_PK PRIMARY KEY (PO_CODE, SL)
);

-- This is the master table for action matrix. It holds the main information about the action matrix.
CREATE TABLE ACM_MASTER (
    ACM_ID VARCHAR2(60),
    PO_CODE VARCHAR2(5) NOT NULL,
    VISITING_DATE DATE NOT NULL,
    
    OBSERVATION_DEPT VARCHAR2(60), -- OPERATION/AUDIT
    
    OBSERVATION_CATEGORY VARCHAR2(500), -- FINANCIAL/OPERATIONAL
    VISIT_TYPE VARCHAR2(20) NOT NULL, -- ONSITE/OFFSITE
    VISIT_CATEGORY VARCHAR2(60), -- REGULAR VISIT/MANAGEMENT AUDIT
    
    LETTER_ISSUE_DATE DATE NOT NULL, 
    LETTER_RESPONSE_DATE DATE, -- TENTATIVE DATE TO GET RESPONSE FROM PO
    
    PKSF_OBSERVATION CLOB,
    DIRECTION_TO_PO CLOB,
    
    ACTION_MATRIX CHAR(1), -- Y/N
    
    PO_INBOX CHAR(1), -- Y/N
    IS_EDITABLE_BY_PO CHAR(1), -- Y/N
    PRIORITY VARCHAR2(10), -- HIGH/MEDIUM/LOW
    
    CREATED_BY VARCHAR2(20),
    CREATED_AT DATE,
    UPDATED_BY VARCHAR2(20),
    UPDATED_AT DATE,
    
    STATUS VARCHAR2(50), -- FINAL STATUS. RUNNING/COMPLETED/CLOSED/DRAFT
    CONSTRAINT PK_ACM_MASTER PRIMARY KEY (ACM_ID)
);

-- This is the file attachment table for acm master.
CREATE TABLE ACM_MASTER_FILE_ATTACHMENT (
    ACM_ID VARCHAR2(60),
    SL NUMBER,
    
    FILE_NAME VARCHAR2(400),
    FILE_PATH VARCHAR2(1000) NOT NULL,
    FILE_TYPE VARCHAR2(20),
    FILE_SIZE NUMBER, 
    
    CREATED_BY VARCHAR2(100),
    CREATED_AT DATE,
    CONSTRAINT PK_ACM_MASTER_FILE_ATTACHMENT PRIMARY KEY (ACM_ID, SL),
    CONSTRAINT FK_ACM_MFA_MASTER FOREIGN KEY (ACM_ID) REFERENCES ACM_MASTER(ACM_ID)
);

-- This is the movement table for acm master. It holds the movement information of acm master.
CREATE TABLE ACM_MOVEMENT (
    ACM_ID VARCHAR2(60),
    SL NUMBER,
    
    FROM_PARTY VARCHAR2(20) NOT NULL, -- PKSF/PO
    ITEM_FROM VARCHAR2(20),
    
    TO_PARTY VARCHAR2(20) NOT NULL, -- PKSF/PO
    ITEM_TO VARCHAR2(20),
    
    ACTION_TYPE VARCHAR2(60), -- This is optional. FORWARD/BACKWARD/APPROVED
    REMARKS CLOB,
    
    STATUS VARCHAR2(50), -- DEFAULT STATUS: RUNNING
    
    CREATED_AT DATE,
    CREATED_BY VARCHAR2(20),
    CONSTRAINT PK_ACM_MOVEMENT PRIMARY KEY (ACM_ID, SL),
    CONSTRAINT FK_ACM_MOV_MASTER FOREIGN KEY (ACM_ID) REFERENCES ACM_MASTER(ACM_ID)
);

-- This is the comments table for acm master. It holds the comments information of acm master.
CREATE TABLE ACM_COMMENTS (
    ACM_ID VARCHAR2(60),
    SL NUMBER,
    
    COMMENT_SOURCE VARCHAR2(20) NOT NULL, -- PKSF/PO
    
    COMMENT_SHORT VARCHAR2(20), -- EKMOT/DIMOT
    COMMENT_DETAIL CLOB NOT NULL, -- ACTUAL COMMENT
    
    CREATED_BY VARCHAR2(100),
    CREATED_AT DATE,
    UPDATED_BY VARCHAR2(100),
    UPDATED_AT DATE,
    CONSTRAINT PK_ACM_COMMENTS PRIMARY KEY (ACM_ID, SL),
    CONSTRAINT FK_ACM_COM_MASTER FOREIGN KEY (ACM_ID) REFERENCES ACM_MASTER(ACM_ID)
);

-- This is the file attachment table for acm comments.
CREATE TABLE ACM_COMMENTS_FILE_ATTACHMENT (
    ACM_ID VARCHAR2(60),
    SL NUMBER,
    FILE_ID NUMBER, -- FILE COUNTER. 1 COMMENT CAN HAVE MULTIPLE FILES
    
    FILE_UPLOAD_BY VARCHAR2(10), -- PO/PKSF
    
    FILE_NAME VARCHAR2(400),
    FILE_PATH VARCHAR2(1000) NOT NULL,
    FILE_TYPE VARCHAR2(20),
    FILE_SIZE NUMBER, 
    
    CREATED_BY VARCHAR2(100),
    CREATED_AT DATE,
    CONSTRAINT PK_ACM_COMMENTS_FILE_ATTACHMENT PRIMARY KEY (ACM_ID, SL, FILE_ID),
    CONSTRAINT FK_ACM_CFA_COMMENTS FOREIGN KEY (ACM_ID, SL) REFERENCES ACM_COMMENTS(ACM_ID, SL)
);
